spring:
  datasource:
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.125.38
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
  dubbo:
    application:
      name: ray-iflow-rpc-service
      registry: zookeeper://192.168.125.161:2183
    protocol:
      id: dubbo
      name: dubbo
      port: 20881
      status: server
sharding:
  jdbc:
    dataSource:
      names: master0,master0-slave1,master0-slave2
      # 配置主库
      master0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.125.161:36005/iflow?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
        username: root
        password: enc:jEhi6SfY38B7rIB9wrFZ1w==
        driver-class-name: com.mysql.cj.jdbc.Driver
      master0-slave1: # 配置第一个从库
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.125.161:36006/iflow?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
        username: root
        password: enc:jEhi6SfY38B7rIB9wrFZ1w==
        driver-class-name: com.mysql.cj.jdbc.Driver
      master0-slave2: # 配置第二个从库
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.125.161:36007/iflow?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
        username: root
        password: enc:jEhi6SfY38B7rIB9wrFZ1w==
        driver-class-name: com.mysql.cj.jdbc.Driver
    config:
      masterslave: # 配置读写分离
        load-balance-algorithm-type: round_robin # 配置从库选择策略，提供轮询与随机，这里选择用轮询//random 随机 //round_robin 轮询
        name: db1s2
        master-data-source-name: master0
        slave-data-source-names: master0-slave1,master0-slave2

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8085

mybatis-plus:
  datasource: dataSource
  mapper-locations: classpath*:/mappers/**/**Mapper.xml
  typeAliasesPackage: com.mrray.ray.iflow.dao.base.model
  configuration:
    cache-enabled: false

