spring:
  datasource:
    url: jdbc:mysql://${APP_DATABASE_HOST:192.168.125.161}:${APP_DATABASE_PROT:36001}/${APP_DATABASE_NAME:iflow}?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
    username: ${APP_DATABASE_USERNAME:root}
    password: ${APP_DATABASE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  dubbo:
    application:
      name: ray-iflow-rpc-service
      registry: zookeeper://192.168.125.161:2183
    protocol:
      id: dubbo
      name: dubbo
      port: 20881
      status: server

server:
  tomcat:
    uri-encoding: UTF-8
  port: ${APP_SERVER_PORT:8085}

# 配置參考https://mp.baomidou.com/config/
mybatis-plus:
  mapper-locations: classpath*:/mappers/**/**Mapper.xml
  typeAliasesPackage: com.mrray.ray.iflow.dao.base.model
  #typeEnumsPackage: cn.mrray.raybaas.dataflow.core.enums,cn.mrray.raybaas.dataflow.model.bank.entity.enums
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

service:
  version: 1.0.0
