server:
  tomcat:
    uri-encoding: UTF-8
  port: ${APP_SERVER_PORT:8086}

spring:
  datasource:
    url: jdbc:mysql://${APP_DATABASE_HOST:192.168.125.161}:${APP_DATABASE_PROT:36001}/${APP_DATABASE_NAME:iflow}?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
    username: ${APP_DATABASE_USERNAME:root}
    password: ${APP_DATABASE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  dubbo:
    application:
      name: ray-iflow-admin
      registry: zookeeper://192.168.125.161:2183
