server:
  tomcat:
    uri-encoding: UTF-8
  port: ${APP_SERVER_PORT:8086}

spring:
  dubbo:
    application:
      name: ray-iflow-admin
      registry: zookeeper://192.168.125.161:2183
swagger:
  enabled: true
  description: iflow流程引擎接口
  title: iflow流程引擎接口
  version: 1.0.0
  base-package: com.mrray.ray.iflow.admin.controller.base
  contact:
    name: lyc
    url: lyc.com
    email: lycxinyue@163.com